### ISSUE TITLE
Failed to activate the urban-syntax theme

### ISSUE THREAD

**Issue by adgai19** [divadretlaw/urban-syntax#1]
[Enter steps to reproduce:]

1. ...change syntex theme
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04
**Thrown From**: [urban-syntax](https://github.com/divadretlaw/urban-syntax) package 1.0.3

### Stack Trace

Failed to activate the urban-syntax theme

```
At variable @dark-green is undefined in /home/aditya/.atom/packages/urban-syntax/base/urban.less:380:11

LessError: variable @dark-green is undefined
at /home/aditya/.atom/packages/urban-syntax/base/urban.less:380:11
```

### Commands

```
```

### Non-Core Packages

```
seti-ui 1.10.0 
teletype 0.13.2 
urban-syntax 1.0.3 
```

**Comment by divadretlaw** [comment]
Was fixed in `1.0.4`
